### ISSUE TITLE
音频特征提取

### ISSUE THREAD

**Issue by 19503610382** [S007-Chen/ADPN-MM#3]
请问音频特征是如何提取的，相关代码可以参考一下吗

**Comment by rapdodo** [comment]
代码跑不通啊大佬
Traceback (most recent call last):
  File "main.py", line 117, in <module>
    for data in tqdm(train_loader, total=num_train_batches, desc='Epoch %3d / %3d' % (epoch + 1, configs.epochs)):
  File "/root/miniconda3/envs/adpn/lib/python3.7/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/root/miniconda3/envs/adpn/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/root/miniconda3/envs/adpn/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 671, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/root/miniconda3/envs/adpn/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/envs/adpn/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/autodl-fs/data/FL/ADPN-MM/util/data_loader.py", line 21, in __getitem__
    video_feature = self.video_features[record['vid']]
KeyError: 'UETKQ'
显示在字典中访问了不存在的key。

**Comment by hlchen23** [comment]
音频特征提取是PANN模型和VGGish模型。

**Comment by hlchen23** [comment]
检查一下数据集是否完备。
